### ISSUE TITLE
FUTURE SCOPE: automate AWS backups

### ISSUE THREAD

**Issue by bess** [curationexperts/cypripedium#287] opened 2018-12-12 15:37 UTC
Currently cypripedium backups are happening manually, and only the volume is being backed up. We have found that an AMI snapshot, performed while the system is turned off, is the easiest most reliable way to recover in the event of emergency. 

We should automate AMI snapshots for cypripedium-prod

**Comment by mark-dce** [comment] 2018-12-17 16:23
duplicate of #288

**Closed as completed by mark-dce** 2018-12-17 16:23 UTC
Labels: duplicate
